name: CI/CD Pipeline

on:
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'
    workflow_dispatch:

jobs:
    pipeline:
        uses: oberon-oss/github-workflows/.github/workflows/maven-pipeline.yml@3180b758e3c4a5d7da9d0f34dfc8fe0678e8fa4e
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
            NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
